config/routes.rb
Rails.application.routes.draw do
  resources :idioms, only: [:index, :show, :new, :create]
  resources :implementations, only: [:show]

end

app/models/idiom.rb
class Idiom < ActiveRecord::Base
  has_many :implementations
end

app/models/implementation.rb
class Implementation < ActiveRecord::Base
  belongs_to :idiom
  belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :implementations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/idioms_controller.rb
class IdiomsController < ApplicationController

  def index
    @idioms = Idiom.all
  end

  def show
    @idiom = Idiom.
      includes(implementations: :language).
      find(params[:id])
  end

  def new
  end

  def create
  end
end

app/controllers/implementations_controller.rb
class ImplementationsController < ApplicationController

  def show
    @implementation = Implementation.
      joins(:idiom, :language).
      find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idioms_helper.rb
module IdiomsHelper
end

app/views/idioms/index.html.haml
= render 'shared/breadcrumbs', breadcrumbs: ['Idioms']

%h1 Idioms
- if @idioms.present?
  %ul
    - @idioms.each do |idiom|
      %li
        = link_to idiom.name, idiom_path(idiom), title: idiom.description
        \-
        = idiom.description

app/views/idioms/new.html.haml
<h1>Idioms#new</h1>
<p>Find me in app/views/idioms/new.html.erb</p>

app/views/idioms/show.html.haml
= render 'shared/breadcrumbs', breadcrumbs: [ |
  link_to('Idioms', idioms_path), |
  @idiom.name]

%h1= @idiom.name
%p
  %i= @idiom.description

- if @idiom.implementations.present?
  %ul.results
    - @idiom.implementations.each do |implementation|
      %li.panel
        %p
          = implementation.language.name
        %pre
          %code= implementation.code
        = link_to 'More', implementation_path(implementation), class: 'button'

app/views/implementations/show.html.haml
= render 'shared/breadcrumbs', breadcrumbs: [ |
  link_to('Idioms', idioms_path), |
  link_to(@implementation.idiom.name, idiom_path(@implementation.idiom)), |
  @implementation.code]

%h1= @implementation.idiom.name
%p
  %i= @implementation.idiom.description

%p= @implementation.language.name
%code= @implementation.code
%p= @implementation.explanation

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_breadcrumbs.html.haml
%nav.breadcrumbs{ role: 'menubar', 'aria-label' => 'breadcrumbs' }
  - breadcrumbs.each do |breadcrumb|
    - if breadcrumb == breadcrumbs.last
      %li.current{ role: 'menuitem' }= breadcrumb
    - else
      %li{ role: 'menuitem' }= breadcrumb